zeebe.client:
  broker.gatewayAddress: 127.0.0.1:26500
  security.plaintext: true
  worker.threads: 3
  worker.maxJobsActive: 1000

server:
  port: 8090

management:
  endpoints:
    web:
      exposure:
        include: "*"