global:
  scrape_interval:     5s # By default, scrape targets every 15 seconds.
  evaluation_interval: 5s

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  - job_name: 'spring-boot-app'
    scrape_interval: 5s
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['host.docker.internal:8090']

  - job_name: 'cluster-gateway'
    metrics_path: /metrics
    static_configs:
      - targets: ['192.168.1.142:9600']
        labels:
          namespace: 'local'
          pod: 'cluster-gateway'

  - job_name: 'broker-0'
    metrics_path: /metrics
    static_configs:
      - targets: ['192.168.1.142:19600']
        labels:
          namespace: 'local'
          pod: 'broker-0'

  - job_name: 'broker-1'
    metrics_path: /metrics
    static_configs:
      - targets: ['192.168.1.142:29600']
        labels:
          namespace: 'local'
          pod: 'broker-1'

  - job_name: 'broker-2'
    metrics_path: /metrics
    static_configs:
    - targets: ['192.168.1.142:39600']
      labels:
        namespace: 'local'
        pod: 'broker-2'